export const vietnamAirportIataList = {
  BMV: 'Buôn Ma Thuột',
  CAH: 'Cà Mau',
  CXR: 'Cam Ranh',
  DAD: 'Đà Nẵng',
  DIN: 'Điện Biên',
  DLI: 'Lâm Đồng',
  HAN: 'Hà Nội',
  HPH: 'Hải Phòng',
  HUI: 'Thừa Thiên Huế',
  PQC: 'Phú Quốc',
  PXU: 'Pleiku',
  SGN: 'TP. Hồ Chí Minh',
  TBB: 'Tuy Hòa',
  THD: 'Thanh Hóa',
  UIH: 'Quy Nhơn',
  VCA: 'Cần Thơ',
  VCL: 'Quảng Nam',
  VCS: 'Côn Đảo',
  VDH: 'Đồng Hới',
  VDO: 'Vân Đồn',
  VKG: 'Rạch Giá',
  VII: 'Vinh',
  VTG: 'Vũng Tàu',
};
